development:
  adapter: sqlite3
  database: db/dev.sqlite3

test:
  adapter: sqlite3
  database: db/test.sqlite3

production:
  adapter: mysql
  database: ceag
  username: ceag
  password: truzecut
  host: localhost
